name: Run Tests and Upload Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
          check-latest: true

      - name: Install dependencies
        run: go mod tidy

      - name: Install xclip
        run: |
          sudo apt-get update
          sudo apt-get install -y xclip

      - name: Run tests and generate coverage (using Xvfb)
        run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" \
          go test ./... -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage.out
          fail_ci_if_error: true

      - name: Extract total coverage
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//' > coverage.txt

      - name: Upload coverage percentage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-percentage
          path: coverage.txt
