name: Run Tests and Upload Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          check-latest: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xclip xsel xvfb

      - name: Start virtual display (Xvfb)
        run: Xvfb :99 -screen 0 1024x768x16 &
      
      - name: Set DISPLAY environment variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run tests and generate coverage
        run: go test ./... -coverprofile=coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: coverage.out
          fail_ci_if_error: true

      - name: Extract total coverage
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//' > coverage.txt

      - name: Upload coverage percentage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-percentage
          path: coverage.txt
