name: Build and Release

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Configurar Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24
          check-latest: true

      - name: Verificar versão do Go e dependências
        run: |
          go version
          go env
          go mod tidy

      - name: Obter versão do Git Tag
        id: get_version
        run: echo "VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Compilar Binário
        run: |
          BIN_NAME="totp-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "windows" ]; then BIN_NAME="${BIN_NAME}.exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -ldflags "-X 'github.com/JVitoroliv3ira/termotp/internal/version.Version=${VERSION}'" -o $BIN_NAME

      - name: Criar Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: totp-${{ matrix.os }}-${{ matrix.arch }}
          path: totp-${{ matrix.os }}-${{ matrix.arch }}*

  release:
    name: Criar Release no GitHub
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v4

      - name: Obter Artefatos dos Builds
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Criar Release com Instruções de Instalação
        uses: softprops/action-gh-release@v2
        with:
          body: |
            # 🚀 TermOTP - Versão ${{ github.ref_name }}

            **TermOTP** é um gerador de códigos TOTP no terminal, ideal para autenticação 2FA.

            ## 📥 Como Instalar
            
            ### 🔹 **Linux**
            **⚠️ Importante:** Para instalar corretamente, os seguintes comandos devem ser executados no terminal:

            ```sh
            # Remover versão antiga, se existir
            sudo rm -f /usr/local/bin/totp

            # Baixar a versão mais recente do TermOTP
            wget https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/totp-linux-amd64 -O totp

            # Dar permissão de execução ao binário
            chmod +x totp

            # Mover o executável para um local acessível globalmente (precisa de sudo)
            sudo mv totp /usr/local/bin/
            ```

            **Agora você pode executar `totp` de qualquer lugar no terminal!** 🚀

            ### 🔹 **Windows**
            **⚠️ Importante:** Para instalar, execute o PowerShell como **Administrador** antes de rodar os comandos abaixo!

            ```powershell
            # Remover versão antiga, se existir
            Remove-Item "C:\Program Files\TermOTP\totp.exe" -ErrorAction SilentlyContinue

            # Criar pasta de instalação (caso ainda não exista)
            mkdir "C:\Program Files\TermOTP" -ErrorAction SilentlyContinue

            # Baixar a versão mais recente do TermOTP
            Invoke-WebRequest -Uri "https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/totp-windows-amd64.exe" -OutFile "C:\Program Files\TermOTP\totp.exe"

            # Adicionar TOTP ao PATH do sistema
            [System.Environment]::SetEnvironmentVariable("Path", $Env:Path + ";C:\Program Files\TermOTP", [System.EnvironmentVariableTarget]::Machine)
            ```

            **Agora reinicie o terminal e rode `totp` de qualquer lugar!** 🚀

            ## 📖 Como Usar o TermOTP
            - **Adicionar uma conta**: `totp setup --name google`
            - **Listar códigos TOTP**: `totp list`
            - **Copiar um código para o clipboard**: `totp copy --name google`

            🔹 *Se curtiu, deixa uma ⭐ no repositório!*
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
